### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by soul-wish** [Aneistazzzzia/aneistazzzzia.github.io#1]
Настя, у меня пара вопросов:

- чем именно ты бы хотела заниматься? Имею ввиду направление (front-end, back-end, QA)?
- что такое "структурный код"?

**Comment by Aneistazzzzia** [comment]
Доброе утро, мне бы хотелось заниматься front-end. В понятие "Структурный код", я имела ввиду программирование на языках С++, С#, Delphi, Assembler

**Comment by soul-wish** [comment]
Понял, спасибо :)
